#compilar o front
FROM node:20.10.0 AS build

ARG VITE_APP_PUBLIC_PATH
ARG VITE_APP_DEV_PORT
ARG VITE_API_ENDPOINT

COPY ./webapp /home/equatorial/webapp/

WORKDIR /home/equatorial/webapp

RUN npm install
RUN npm run build

# executando ngnix para os arquivos compilados
FROM nginx:alpine

COPY --from=build /home/equatorial/webapp/dist/ /usr/share/nginx/html/
ADD ./config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]